title: "Dr. Rekha Mandloi"
description: "Hindi poet and writer"
baseurl: ""
url: "https://rekhamandloi.github.io"
lang: "en"

# Collections
collections:
  poems:
    output: true
    permalink: /poems/:name/
  stories:
    output: true
    permalink: /stories/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "poems"
    values:
      layout: "poem"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

# Build
markdown: kramdown
kramdown:
  input: GFM

# Prevent SCSS processing of plain CSS
sass:
  sass_dir: _sass
  style: compressed
